FROM php:5.6-apache
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN apt-get update -y && apt-get install -y curl && apt-get clean -y
RUN docker-php-ext-install mysqli
# RUN docker-php-ext-install curl